config/routes.rb
HudhudHouse::Application.routes.draw do
  match "site_scraper/*id" => "site_scraper#index", :as => :site, :id => /.+/

  get "location/where_we_are", :as => :our_location
  get "aboutus" => "pages#aboutus"
  get "contact" => "pages#contact"
  get "pages/main"
  get "books/financial_software"
  get "pages/main2"
  match "mongo-rails-backbone-setup" => 	"pages#mongo_rails_backbone_setup", :as => :mongo_rails_backbone_setup
  match "pages/portfolio/:id" => "pages#portfolio", :as => :portfolio
  root :to => "pages#main"
  match "pages/get_listing" => "pages#get_listing", :as => :get_listing
  match "blog/:id" => "pages#blog", :as => :blog
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include BooksHelper
  layout "book"
  def rails
    initialize_rails_books
  end

  def javascript
    initialize_js_books
  end

  def databases
  end

  def financial_software
    page = params[:page] || 1 # use page, or use the first page
    return render folder_path("financial_software") + "/chapter_#{page}"
  end

  def algorithms
  end

  def miscellaneous
  end

  def ubuntu_setup
  end
  
  private
  def folder_path(key)
    "/books/#{key}"
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def where_we_are
    render layout: 'book'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include PagesHelper
  def main
  end
  def main2
  end
  def portfolio
    @type = params[:id]
  end
  def mongo_rails_backbone_setup
    render :creating_mongo_and_backbone_app and return
  end
  def file_upload_with_carrier_wave_and_fog
    render :file_upload_with_carrier_wave_and_fog and return
  end

  def get_listing
  end

  def blog
    id = params[:id]
    (render( {:template => "pages/#{id}", :layout => "book"}) if (all_blogs.values.flatten).include?(params[:id])) and return
  end
  def aboutus
  end

end

app/controllers/site_scraper_controller.rb
class SiteScraperController < ApplicationController
  def index
    url = params[:id]
    @session ||= Patron::Session.new
    page_source = @session.get(url)
    render text: page_source.body
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include PagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def initialize_rails_books
    chapters = []
    
  end
  def initialize_js_books
    @chapters = [["How to Learn Javascript - A Short Course Outline", "javascript_course_outline"],
      ["Javascript Reference Implementations for Common Patterns", "javascript_patterns"],
      ["How to add inline child forms on the parent form in javascript -- Inline Child Forms", "inline_forms"]
    ]
  end
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def portfolio_for
    case @type
      when "rails"
        list = []
        list << image_tag("portfolio/rails/39shops.com")
        list << image_tag("portfolio/rails/assembla.com")
        list << image_tag("portfolio/rails/campusrock.com")
        list << image_tag("portfolio/rails/decodon.com")
        list << image_tag("portfolio/rails/homeschoolmaster.com")
        list << image_tag("portfolio/rails/mpifix.com")
        list << image_tag("portfolio/rails/olery.com")
        list << image_tag("portfolio/rails/underthesite.com")
      when "javascript"
        list = []
      when "php"
        list = []
        list << image_tag("portfolio/php/clickfuel.com")
        list << image_tag("portfolio/php/urfilez.com")
    end
    list
  end
  def all_blogs
    {
      :detailed => detailed,
      :needs_work => needs_work
    }
  end
  def render_index
    x = detailed
    y = needs_work if params[:complete_index]
    x = x + y if y
    links = []
    x.each do |title, filepath|
      classes = "left-link"
      classes += " highlight" if filepath.match(/#{params[:id]}/i) && params[:id].present?
      if params[:complete_index]
        links << "<li>" + link_to(title, blog_path(filepath, :complete_index => true), :class => classes ) + "</li>"
      else
        links << "<li>" + link_to(title, blog_path(filepath), :class => classes ) + "</li>"
      end
    end
    ("<ol>" + links.join + "</ol>").html_safe
  end
  def render_right_panel
    classes = "right-link"
      classes += " highlight" if our_location_path.match request.fullpath
 
    ("<ul>" + link_to("Our Location", our_location_path, :class => classes) + "</ul>").html_safe
  end
  def detailed
  [["How to Learn Javascript - A Short Course Outline", "javascript_course_outline"],
  ["Javascript Reference Implementations for Common Patterns", "javascript_patterns"],
  ["Miscellaneous Problems Encountered in Development and Their Solutions", "problem_based_learning"],
  ["Set Up and Configure Postgresql on Ubuntu for Rails Development", "postgres_setup"],
  ["How to add inline child forms on the parent form in javascript -- Inline Child Forms", "inline_forms"]
  ]
  end
  def needs_work
    [
    #["Some Simple Mongoid Commands to Get Started", "mongoid_simple_commands"],
    #["Salesforce App Development", "salesforce_app"],
    ["List of Personal Projects", "projects_for_development"],
    ["Machine Learning Course Notes", "machine_learning"],
    ["Machine Learning Exam Prep", "test_preparation_for_machine_learning"],
    ["Octave Installation and Basics for Mathematical Programming", "octave_1"],
    ["Javascript Effects Garden", "javascript_effects"],
    #["Survey of Javascript/Jquery Effects", "js_effects"],
    ["Interesting Stuff", "javascript_crockford"],
    ["File Upload with Carrier Wave and Fog", "file_upload_with_carrier_wave_and_fog"],
    ["Rspecs and Testing", "rspecs"],
    ["How to Ajaxify Form Submission in Rails", "ajaxify_form_submission"],
    ["Setting Up Dev machine", "setting_up_dev_machine"]]

  end
  def portfolio_first_for
    str = ""
    case @type
      when "rails"
        str = image_tag("portfolio/rails/first_one-aboutus.org")
      when "javascript"
        str = image_tag("portfolio/javascript/first_one-profitably.com")
      when "php"
        str = image_tag("portfolio/php/first_one-mpoc.org.pk")
    end
    str
  end
end

app/helpers/site_scraper_helper.rb
module SiteScraperHelper
end

app/views/books/algorithms.html.haml
%h1 Books#algorithms
%p Find me in app/views/books/algorithms.html.haml

app/views/books/databases.html.haml
%h1 Books#databases
%p Find me in app/views/books/databases.html.haml

app/views/books/financial_software/chapter_1.html.haml
%h2 Chapter 1
%h3 Due Date Calculations for Monthly/Periodic Payments

%div
  A user subscribes on any day, and then he needs to be charged every x days, where x is configurable.
  One wants to be able to charge him every 5 days, or every 10 days, or any given number of days.
  Every invoice records in how many days the user will be charged, and we need to calculate due dates on invoices
  using this rule.
  
%div
  In another scenario, a user signs up on any particular day, and then we need to charge him on the xth of every month.
  This is not like the above case, since we may want to always charge him on the 5th of a month. If the current month is
  January then the user will be charged after 31 days, whereas if the month is February, the user will be charged either after 28 days, or 29 days depending on leap year. We want to make sure that the user is charged on the same day every month.
  
%div
  Associated with the latter case above, there is a typical requirements that if the user subscribes within the first few days of the due date, then we can skip charging him for the first month of use, since he would have used the plan for only a very limited number of days. So let's say, we want to charge on the 30th of every month, but if the user has signed up later than 20th, then we want to charge him starting next month, and skip the first due date.


The code for the first scenario is quite easy. Here it is:

%pre
  %code
    due_date = invoice.creation_date + invoice.every_x_days

The code for the second scnenario is more complicated than above. It needs to be aware of the following things:
%ul
  %li Variable number of month days
  %li If the invoice wants to be charged every 31st, then it needs to charge on the 30th of a month with 30 days
  %li Skipping of days has to be handled carefully

Here is the code for the above scenario:

%pre
  %code
    creation_date = invoice.creation_date
    day, month, year = creation_date.day, creation_date.month, creation_date.year
    if day < due_date_day # the first due date is potentially this month
    \  max_day = creation_date.end_of_month.day
    \  if due_date_day < max_day
    \    final_date = Date.parse("\#{due_date_day}-\#{month}-\#{year}")
    \  else
    \    final_date = Date.parse("\#{max_day}-\#{month}-\#{year}")
    \  end
    else # the due date is next month
    \  next_month_date = creation_date + 1.month # this will be in the next month
    \  d, m, y = next_month_date.day, next_month_date.month, next_month_date.year
    \  max_day = next_month_date.end_of_month.day
    \  if due_date_day < max_day
    \    final_date = Date.parse("\#{due_date_day}-\#{m}-\#{y}")
    \  else
    \    final_date = Date.parse("\#{max_day}-\#{m}-\#{y}")
    \  end
    end
    final_date = final_date + 1.month if (final_date - creation_date < skip_x_days)
    if final_date.day != due_date_day && due_date_day < final_date.end_of_month.day
    \  final_date = Date.parse("\#{due_date_day}-\#{final_date.month}-\#{final_date.year}")
    end

app/views/books/javascript.html.haml
%h1 Books#javascript
%p Find me in app/views/books/javascript.html.haml

app/views/books/miscellaneous.html.haml
%h1 Books#miscellaneous
%p Find me in app/views/books/miscellaneous.html.haml

app/views/books/rails.html.haml
%h1 Books#rails
%p Find me in app/views/books/rails.html.haml

app/views/books/ubuntu_setup.html.haml
%h1 Books#ubuntu_setup
%p Find me in app/views/books/ubuntu_setup.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head

    %title= content_for?(:title) ? yield(:title) : "HudhudHouse"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)




  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} Hudhud House
          .nav-collapse.collapse
            %ul.nav
              %li.active
                %a{:href => "/"} Home
              %li
                %a{:href => "/aboutus"} About
              %li
                %a{:href => "/contact"} Contact
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Blogs
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to("Rails Mongo and Backbone app", mongo_rails_backbone_setup_path)
                  %li
                    = link_to("Basic postgres setup for rails", blog_path("postgres_setup"))
                  %li
                    = link_to("Upload files on Amazon using carrier Wave", blog_path("file_upload_with_carrier_wave_and_fog"))
                  %li.divider
                  %li.nav-header Javascript
                  %li
                    = link_to("Effects", blog_path("javascript_effects"))
                  %li
                    = link_to("Course Outline", blog_path("javascript_course_outline"))
                  %li.divider
                  %li
                    = link_to("Miscellaneous Blog Index", get_listing_path)
  
  
    .container
      = yield

app/views/layouts/book.html.haml
!!!
%html
  %head

    %title= content_for?(:title) ? yield(:title) : "HudhudHouse"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)




  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} Hudhud House
          .nav-collapse.collapse
            %ul.nav
              %li.active
                %a{:href => "/"} Home
              %li
                %a{:href => "/aboutus"} About
              %li
                %a{:href => "/contact"} Contact
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Blogs
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to("Rails Mongo and Backbone app", mongo_rails_backbone_setup_path)
                  %li
                    = link_to("Basic postgres setup for rails", blog_path("postgres_setup"))
                  %li
                    = link_to("Upload files on Amazon using carrier Wave", blog_path("file_upload_with_carrier_wave_and_fog"))
                  %li.divider
                  %li.nav-header Javascript
                  %li
                    = link_to("Effects", blog_path("javascript_effects"))
                  %li
                    = link_to("Course Outline", blog_path("javascript_course_outline"))
                  %li.divider
                  %li
                    = link_to("Miscellaneous Blog Index", get_listing_path)
  
  
    .container
      .row
        .span2
          = render_index
        .span8
          = yield
        .span2
          = render_right_panel

app/views/location/where_we_are.html.haml
.location.displace
  %h2
    We are 
    %span
      %em here
  %img{:src => "http://maps.google.com/maps/api/staticmap?size=400x400&maptype=roadmap&sensor=false&markers=color:blue|label:A|Lahore,PK", :alt => "Lahore, Pakistan"}

app/views/pages/ajaxify_form_submission.html.haml
%h2 How to ajaxify a form
%p
  You are viewing a page of a resource of type Type1, which has many elements of type Type2 associated with it.
%p
  For each element of Type2 displayed, there is a corresponding form, and consequently, a form_for helper.
%p
  But the update action of Type2 responds to html request by showing the resource of Type2, not Type1.
%p
  We need to first submit through ajax, on success, update the displayed element of type Type2 and a flash message,
%p
  and if on failure, need to display the error without updating the attached view, and a flash message.
%p
  So here are the steps:
%p
  if u simply add the option :remote => true to form_for, u will make the submission work. in the controller, 
  if format.js is there, then it will look for the action.js.erb file and render it, so you can write code
  there. But you may want to do something more complicated, example u want callbacks etc. 
%p
  to achieve that, a) tell the controller action not to render anything, just return render :nothing => true
  b) the rails ujs ajax call provides the following actions: (ajax:before, ajax:after, ajax:loading, ajax:success, ajax:failure, ajax:complete, so u can have a separate script, eg a file.js, where u can do stuff like:
%p
  $('some-selector').bind('ajax:success', function(){$(this).closest('elem').fadeIn();}) etc
%p
  So determine how you want to tackle it:
  %pre
    &nbsp;&nbsp;a) inline, may be ugly
    b) handle submission through ajax separate, with the callback right there. want to explore this out more. looks standard esp on other projects. Makes rails stop interacting directly with the js stuff
    c) use rails remote => true, and return a js.erb file using format.js. explore this as well. Doesnt look quite nice though
    d) use rails remote => true, render nothing from controller, and use the provided actions in a separate script. looks railsy and standard. would use this currently, and explore the others later.
    e) user rails remote => true, render some valid response, and same as d)
%p
  see 
  %a{:href => "http://net.tutsplus.com/tutorials/javascript-ajax/using-unobtrusive-javascript-and-ajax-with-rails-3/", :target => "_blank"}this link
%p
  but the controller can do the processing just fine, and return success, but there can be a parsing error
  if the response is not correctly parse (parseerror) so one has to know how to respond, so read up on the 
  format.js options a bit
%p
  steps for option e)
  make sure u are returning valid js response from controller, or even though it is successful it can cause 
  parseerror and therefore ajax:error will execute.

app/views/pages/algorithms_course.html.haml
%h4 Class 1:
%ul

  %li insertion sort
  %li review of O-notation
  %li solve the simple recurrence: T(n) = 2T(n/2)

%h4 Class 2:
%ul
  %li Merge sort recursive
  %li analysis of merge sort using the tree method

%h4 Class 3:
%ul
  %li Loop invariant
  %li Example of outer loop's loop invariant in Insertion sort
  %li Bottom Up Merge sort using the string: "MergeSortIsvFast"
  %li Correction of Error in lecture 2 in calculating index: middle = (p+q)/2
  %li Assign assignment: implement bottom up merge sort using 8^2, 8^4, 8^6, and 8^8 random numbers
  %li Discussion of why MergeSort requires additional space, but couldnt explain example well enough

%h4 Class 4:
%ul
  %li Quick Sort description
  %li Quick Sort as in book is unstable
  
%h4 Class 5:
%ul
  %li QuickSort Analsis
  %li Worst case and Average Case Analysis
  
%h4 Class 6
%ul
  %li Heapsort
  %li Heaport Analysis
  %li Quiz 1 On Quicksort, given an array with all values, 5, apply QuickSort on it, and conclude what is the worst case input
  
%h4 Class 7
%ul
  %li Analysis of Heapify, which takes O(n) time
  %li Count Sort
  %li Introduction of Radix Sort

app/views/pages/contact.html.haml
%h3 Coming Soon...

app/views/pages/file_upload_with_carrier_wave_and_fog.html.haml
%h2 File Upload on Amazon with Carrierwave and Fog

%p
  First, using carrierwave with a script is quite simple. Below is a simple script to demonstrate bare-bones use:
  %br
  %code.blue
    require 'carrierwave'
    %br
    class SimpleUploader < CarrierWave::Uploader::Base
    %br
    &nbsp;&nbsp;storage :file
    %br
    end
    %br
    \# now use it with:
    %br
    uploader = SimpleUploader.new
    %br
    uploader.store!(File.open('path/to/file.png'))
    %br

%p
  The demonstrated how to save files locally. In order to store files on amazon, we first need the fog gem. Once the fog gem is intalled, making carrier wave store on amazon is as easy as adding a configure block, and specifying the storage option as fog like so:
  %br
  %code.blue
    CarrierWave.configure do |config|
    %br
    &nbsp;&nbsp;config.fog_credentials = {
    %br
    &nbsp;&nbsp;&nbsp;&nbsp;:provider => 'AWS',
    \:aws_access_key_id  => 'key',
    \:aws_secret_access_key => 'secret'
    %br
    &nbsp;&nbsp;}
    %br
    &nbsp;&nbsp;config.fog_directory  = 'directory_path'
    %br
    end
    %br
    class SimpleUploader < CarrierWave::Uploader::Base
    %br
    &nbsp;&nbsp;storage :fog
    %br
    end

app/views/pages/get_listing.html.haml
%div.floater-left
  %h3.heading-green
    Blogs And Tutorials in Fine Shape
  %ol
    - all_blogs[:detailed].each do |title, blog|
      %li= link_to(title, blog_path(blog))

%div.floater-left
  %h3.heading-green
    Incomplete/Abandoned Material for Blogs
  %ol
    - all_blogs[:needs_work].each do |title, blog|
      %li= link_to(title, blog_path(blog))

%div.clear

app/views/pages/javascript_course_outline.html.haml
%h2.heading-green
  How to Learn Javascript - A Short Course Outline

%h3#basics
  Basics
%ol
  %li
    Variable Declaration
    = link_to("Variable Declaration", "http://www.google.com/search?q=Javascript+Variable+Declaration", :target => "_blank")
  %li
    Local Variables vs Global Variables
    = link_to("Local variables", "http://www.google.com/search?q=Javascript+Local+Variables", :target => "_blank")
    = link_to("Global variables", "http://www.google.com/search?q=Javascript+Global+Variables", :target => "_blank")
  %li
    If Conditions
    = link_to("If Conditions", "http://www.google.com/search?q=Javascript+If+Conditions", :target => "_blank")
  %li
    Looping
    = link_to("Looping", "http://www.google.com/search?q=Javascript+Looping", :target => "_blank")
%h3#foundation-1
  Foundation I
%ol
  %li
    Anonymous Functions (Closely Related to Closures)
    = link_to("Anonymous Functions", "http://www.google.com/search?q=Javascript+Anonymous+Functions", :target => "_blank")
  %li
    Closures (Closely Related to Anonymous Functions)
    = link_to("Closures", "http://www.google.com/search?q=Javascript+Closures", :target => "_blank")
  %li
    Prototype-Based Inheritance
    = link_to("Prototype-Based Inheritance", "http://www.google.com/search?q=Javascript+Prototype+Based+Inheritance", :target => "_blank")
  %li
    Object Model
    = link_to("Object Model", "http://www.google.com/search?q=Javascript+Object+Model", :target => "_blank")
%h3#foundation-2 Foundation II
%ol
  %li
    Classes
    = link_to("Classes", "http://www.google.com/search?q=Javascript+Classes", :target => "_blank")
  %li
    Inheritance
    = link_to("Inheritance", "http://www.google.com/search?q=Javascript+Inheritance", :target => "_blank")
  %li
    Module Pattern
    = link_to("Module Pattern", "http://www.google.com/search?q=Javascript+Module+Pattern", :target => "_blank")
%h3#web-development
  Web Development Concepts
%ol
  %li
    Events
    = link_to("Events", "http://www.google.com/search?q=Javascript+Events", :target => "_blank")
  %li
    Effects
    = link_to("Effects", "http://www.google.com/search?q=Javascript+Effects", :target => "_blank")  
  %li
    Ajax
    = link_to("Ajax", "http://www.google.com/search?q=Javascript+Ajax", :target => "_blank")  
  %li
    Plotting
    = link_to("Plotting", "http://www.google.com/search?q=Javascript+Plotting", :target => "_blank")  

%h2.heading-green
  Why the Above Course Outline?

Javascript is quite different from other languages like Ruby, Java, C++ etc. Getting comfortable with javascript involves 3 key steps, followed by learning javascript for web development:
%ol
  %li
    Knowing javascript syntactic details, much like getting the syntax in other languages. This is covered in the
    = link_to("Basics", "#basics")
    section.
  %li
    Knowing certain key concepts that are part of javascript, but are not part of other classic languages most developers are familiar with. This takes some getting used to. They are covered in the
    = link_to("Foundation I", "#foundation-1")
    section.
  %li
    Once you are comfortable with javascript syntax and key concepts, you need to implement familiar concepts that you learned in other languages. The following are widespread patterns and concepts in other languages, and typically we program using these familiar patterns/concepts:
    %ul
      %li Classes
      %li Inheritance
      %li Modules
    So the next step to learning javascript is to learn how to implement the above key concepts in javascript. This is covered in
    = link_to("Foundation II", "#foundation-2")
    section.
  %li
    One typically learns javascript for client-side programming. Roughly speaking, javascript is great for events, effects, plotting, and ajax among other things. Typically when one begins web development, one spends time learning only the Basics, followed by getting familiar with the concepts in the
    = link_to("Web Development", "#web-development")
    section. Therefore the final part of learning javascript is to learn how it is used for client side programming. This is covered in
    = link_to("Web Development Concepts", "#web-development")
    section.

app/views/pages/javascript_crockford.html.haml
%h3
  Crockford Talk on Javascript

%div
https://balinterdi.leadpages.net/emberjs-mailing-list/?subdomain=balinterdi 

https://balinterdi.leadpages.net/emberjs-mailing-list/?subdomain=balinterdi
  =link_to("Crockford of Programming Style and Your Brain", "https://www.youtube.com/watch?v=taaEzHI9xyY&feature=youtube_gdata_player")
  =link_to("Js lint", "http://www.jslint.com")
The gut informs the head. The head uses those. The head is not usually aware of those. So it is easy to confuse ppl by confusing the guts.

The ppl know this are the advertising industry. they create wants/needs which you dont need.

You sell tobacco to the gut.

Programming 

app/views/pages/machine_learning_programming.html.haml
%ul
  %li
    typically X = a column vector. Adding ones to take care of theta-0 corresponds to inserting a column of 1's to the left of X, thus making X into a m*2 matrix, where the first column is all ones, the second column is the X values. You then multiple it by theta-vector, which is also a column vector.
  %li
    for gradient descent, inner loop to update theta, use vectorized implementation instead of looping on theta-j for each j,
    and this is covered in "Vectorization".
  %li
    In programming, adding input 1 to X is like "coordinate lifting"; if data is 1-d, it becomes 2-d, if n-d, it becomes n+1-d and so on
  %li
    Linear regression exercises are done.
%ul
  %li
    Exercise 2
  %li
    Looks like we need to extract the y=1 values and y=0 values, and then plot the y=1 values in a diff color and marker and so on. basically a find(condition) followed by feeding the indices into two plot functions
  %li
    exercice one is a good one on plotting data, refer to it.
  

app/views/pages/main2.html.haml
.hero-unit
  .span4.offset4
    %h2 Lets Learn Together
    
.row
  .span4.offset4
    %h3 Index
    = render_index

app/views/pages/mongoid_simple_commands.html.haml
:css
  .inner {margin-left: 2%;}
%div
  As a base, use the following:
  %div.inner
    class User
    %div.inner
      include Mongoid::Document
      %br
      field :username, type: String
      %br
      field :email, type: String
      %br
      field :age, type: Integer
      %br
    end

%h3
  Add column
%h3
  Remove column
%h3
  Change column type
%h3
  Drop table
%h3
  Add index
%h3
  Remove index
%h3
  Drop all records
%h3
  change all names to upcase

app/views/pages/projects_for_development.html.haml
%h1 Overview
In order to improve programming skills, I should pick up some projects and work on them.
I dont have to try and take a project to completion; I only have to pick up a project and
work on it enough that I get some fullfillment out of it, and I learn something new. I may
then decide to switch to another project, or have more than one ongoing.

There are many ideas for projects. One simple idea is to explore as much open source code as possible in
a select few languages. This should increase my ability to read code, and expose me to new ways
of writing code. I may also use these to better understand the api's I interact with during professional
development.

Hopefully after exploring a dozen or so projects, I may get an idea of what to build for myself. I may
then try and build that.

%h3 Build a JSlint for Ruby (Python later).

%h4 Attack Plan.
%table.green-table
  %thead
    %tr
      %th
        Task
      %th
        Estimated number of days
      %th
        Days spent?
      %th
        Do I feel done?
  %tr
    %td
      Explore JsLint Source Code
    %td
      5
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      Get familiar with ruby metaprogramming
    %td
      7
    %td
      0
    %td
      &#x2717;
  %tr
    %td
      List features for Javascript recommended by jslint
    %td
      3
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      List features of Javascript discouraged by jslint
    %td
      2
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      Come up with ruby features to recommend
    %td
      4
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      Come up with ruby features to discourage
    %td
      4
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      Code
    %td
      5
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      Look at existing refactoring tools 1
    %td
      4
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      Look at existing refactoring tools 2
    %td
      4
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      compare your code to other code 1
    %td
      2
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      compare your code to other code 2
    %td
      2
    %td
      0
    %td
      &#x2717;
  %tr      
    %td
      Conclusion
    %td
      3
    %td
      0
    %td
      &#x2717;
  %tfoot
    %tr
      %td
        Total
      %td
        45
      %td
        0
      %td
        N/A

app/views/site_scraper/index.html.haml
%h1 SiteScraper#index
%p Find me in app/views/site_scraper/index.html.haml